Add s3 staging
precog/quasar-destination-avalanche pull request #127
Opened 2020-06-05 07:27 UTC by nicflores

2020-06-05 18:02 UTC, djspiewak commented
This is **breaking** since it removes the old `avalanche` destination.

2020-06-05 18:04 UTC, djspiewak requested changes
The `iijdbc.jar` file is duplicated unnecessarily. This should almost certainly be in `core/lib/`.

2020-06-05 18:04 UTC, djspiewak commented on .versions.json
> +  "precog-async-blobstore": "3.0.1-e774822"
I merged the PR so this can now be updated.

2020-06-05 18:14 UTC, djspiewak requested changes

2020-06-05 18:14 UTC, djspiewak commented on azure/src/main/scala/quasar/destination/avalanche/azure/AvalancheAzureDestinationModule.scala
> +    DestinationType("avalanche-azure", 1L)
This needs to be coordinated with the frontend to ensure the UI is appropriately updated.

2020-06-05 18:14 UTC, djspiewak commented on build.sbt
> +//val DoobieVersion = "0.8.8"
Stray comment

2020-06-05 18:14 UTC, djspiewak commented on build.sbt
> +  // )
Stray comments

2020-06-05 18:14 UTC, djspiewak commented on build.sbt
>    .enablePlugins(AutomateHeaderPlugin)
FYI this line isn't needed

2020-06-05 18:14 UTC, djspiewak commented on build.sbt
> +  )
Minor nit: collapse these two lines. We don't generally have dangling closing parentheses in this fashion.

2020-06-05 18:14 UTC, djspiewak commented on build.sbt
> +      "com.precog" %% "async-blobstore-core" % managedVersions.value("precog-async-blobstore")),
Why the separate dependency on `-core`? Presumably it also comes transitively via `-s3`?

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3Config.scala
> +  region: Region)
FYI, we generally double-indent function- and class-definition continuations. So these parameters should all be four-space indented.

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3Destination.scala
> +final case class TableName(value: String)
Did you re-add this after it was removed?

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3Destination.scala
> +      fr"QUOTE" -> fr"""'"'""") ++ fr", AUTO_DETECT_COMPRESSION"
Isn't most of this stuff shared completely with the azure destination? Shouldn't it live in core?

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3DestinationModule.scala
> +object AvalancheS3DestinationModule extends DestinationModule {
There's a LOT of stuff in here which is duplicated from the Azure module and can be factored into core.

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3DestinationModule.scala
> +  }
More or less everything except this.

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3DestinationModule.scala
> +      : F[Either[InitializationError[Json], Unit]] = {
Parameters should be double-indented, just like the return type

2020-06-05 18:14 UTC, djspiewak commented on s3/src/main/scala/quasar/destination/avalanche/s3/AvalancheS3DestinationModule.scala
> +      }
…formatting?

2020-06-05 18:15 UTC, djspiewak commented
So there are some important things to clean up here, but the whole thing is more fundamentally hard-blocked on the frontend catching up with these changes and correctly exposing them in the UI.

2020-06-08 02:34 UTC, nicflores commented
Here's a snapshot of the latest commit: `16.0.7-13daf1b`

2020-06-08 11:03 UTC, rintcius commented on README.md
> +  "writemode": "create" | "replace" | "truncate",
Possible to be consistent with `avalanche-azure` here?

I.e. use these names:
```
  "connectionUri": String,
  "clusterPassword": String,
  "writeMode": "create" | "replace" | "truncate",
```

and nested `credentials` object (which is also used in https://github.com/precog/quasar-destination-s3) ?

```
{
  "bucket": String,
  "credentials": {
    "accessKey": String,
    "secretKey": String,
    "region": String
   }
}

2020-06-08 14:10 UTC, djspiewak commented on azure/src/main/scala/quasar/destination/avalanche/azure/AvalancheAzureDestination.scala
> +          _ <- Stream.eval(copy(tableName, freshName, cols)).onFinalize(deleteBlob(freshName))
NB this should be done with `bracket` rather than `eval` and `onFinalize`, since we will leak the file if we are canceled during the upload.

2020-06-08 14:24 UTC, djspiewak commented on README.md
> +  "writemode": "create" | "replace" | "truncate",
I think it probably doesn't make any sense to use `credentials` for both the top-level and nested keys, but the rest is easy. I'll make the changes.

2020-06-08 14:38 UTC, djspiewak commented
Published as `16.0.7-689a1bd`

2020-06-08 15:19 UTC, merged